### PR TITLE
Update dependency (imlib -> brainglobe-utils)

### PR DESCRIPTION
**Pull request by adamltyson**

### CODE REVIEW

**Review by alessandrofelder — APPROVED** [review]
👍

**Comment by alessandrofelder** [comment]
I'm going to hold off merging this until I'm confident that the CI failures are unrelated to the changes in this PR @adamltyson ... which I _expect_ should be the case?

**Comment by adamltyson** [comment]
I wouldn't have thought so, but weird it's failing on py38 only.

**Comment by alessandrofelder** [comment]
I can't reproduce this failure locally, but I doubt that the changes are the problem, so I will merge and we can tackle this elsewhere.

**Pull request merged**
