### PR TITLE
Prep merge

### LINKED ISSUE #272: How are `prep_classification` and `prep_training` different?
In a PR discussion with @alessandrofelder, we noticed these two functions seem to only vary in the order of their input parameters:
- [prep_classification definition](https://github.com/brainglobe/cellfinder-core/blob/58141d7730dd852044440ba45b6e53702d8d0b63/src/cellfinder_core/tools/prep.py#L23C25-L23C25)
- [prep_training definition](https://github.com/brainglobe/cellfinder-core/blob/58141d7730dd852044440ba45b6e53702d8d0b63/src/cellfinder_core/tools/prep.py#L39)

If both classification and training require the same setup, maybe we can combine them in one function and name it `prep_tensorflow_and_model` or similar?

### PR DESCRIPTION
**Pull request by adamltyson**
Combines two very similar functions and also removes a seemingly redundant function arguement. 

@sfmig I've somewhat naively updated the benchmarking code, but I may have done this wrong.

Closes #272

### CODE REVIEW

**Comment by adamltyson** [comment]
brainmapper updated in https://github.com/brainglobe/brainglobe-workflows/pull/66

**Comment by willGraham01** [comment]
Worth flagging here that when this update and the matching one on `workflows` goes in, we should make new releases for both. (In particular, the `workflows` PR should force a minimum version of `cellfinder` that corresponds to the new release)

**Comment by adamltyson** [comment]
> In the interest of resolving this, I guess we make the brainmapper CI check in this repo optional when creating a release and/or merging a PR? That way we at least have a check which'll indicate when things can potentially go wrong and need to be fixed in workflows too.

Yeah I think that's the way.

**Comment by willGraham01** [comment]
> Yeah I think that's the way.

Have added this change to this branch.

**Comment by willGraham01** [comment]
@adamltyson do you want me to merge this, publish the release, and then try re-running the CI on https://github.com/brainglobe/brainglobe-workflows/pull/66 ?

**Comment by adamltyson** [comment]
Sounds good

**Review by willGraham01 — APPROVED** [review]

**Pull request merged**
