### PR TITLE
Remove modular asv benchmarks

### PR DESCRIPTION
**Pull request by sfmig**
keeping an eye on brainglobe/cellfinder#404 👀 

## Description

**What is this PR**

- [ ] Bug fix
- [ ] Addition of a new feature
- [x] Other

**Why is this PR needed?**
To remove unused benchmarking code.

**What does this PR do?**
Deletes old code that used `asv` to benchmark individual functions of `cellfinder.core`. 

We decided to go for an integrated approach to benchmarking, in which we benchmark a full workflow rather than modules or individual functions. Because of this, we also moved all benchmarking code to [the workflows repository](https://github.com/brainglobe/brainglobe-workflows).

## References

The most relevant issues are brainglobe/brainglobe-workflows#105 and brainglobe/brainglobe-workflows#106, although since then the benchmarking work has moved to [the workflows repository](https://github.com/brainglobe/brainglobe-workflows).

## How has this PR been tested?

The code has been tested locally.

## Is this a breaking change?

No.

## Does this PR require an update to the documentation?

No.

## Checklist:

- [x] The code has been tested locally
- [ ] Tests have been added to cover all new functionality (unit & integration)
- [ ] The documentation has been updated to reflect any changes
- [x] The code has been formatted with [pre-commit](https://pre-commit.com/)

### CODE REVIEW

**Review by alessandrofelder — APPROVED** [review]

**Comment by alessandrofelder** [comment]
PRs that remove things are always nice 🤩 
I've transferred the issues over to the workflows repo... feel free to close them as duplicates if you already have equivalent issues there, @sfmig !

**Comment by adamltyson** [comment]
> We decided to go for an integrated approach to benchmarking, in which we benchmark a full workflow rather than modules or individual functions. Because of this, we also moved all benchmarking code to [the workflows repository](https://github.com/brainglobe/brainglobe-workflows).

Late to the party here, but does this mean that if some changes are made here, we won't find out if they affect the benchmarks until they are run on the workflows repo? I.e. rather than being part of the CI?

**Comment by willGraham01** [comment]
We have [a check in CI](https://github.com/brainglobe/cellfinder/blob/6b529dc72110114f0d17c8139e8645f8fecef317/.github/workflows/test_and_deploy.yml#L101) to make sure that `brainmapper` isn't breaking. We could generalise it to other benchmarks if we want to.

**Comment by adamltyson** [comment]
That would be great if it's not super complicated. The main reason for this effort is to catch performance degradations early.

**Pull request merged**
